		<?php 



function musicbox_artist_profile_from_sub_menu()
{

      $menu['artist/%'] = array(
        'page callback' => 'musicbox_artist_profile_callback',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
  
  return $menu;
}

function musicbox_artist_profile_callback(){
	 print theme('musicbox_artist_mobileview_item');
			

}


function musicbox_artist_profile_from_sub_theme(){
	
	$modulePath = drupal_get_path('module', 'musicbox_artist_profile_from_sub');
	
    $base = array(
        'path' => $modulePath.'/templates',
    );
    $boots_js = $modulePath . '/js/bootstrap.js';
    $bootsmin_js = $modulePath . '/js/bootstrap.min.js';

    $boots_css = $modulePath . '/css/bootstrap.css';
    $main_css = $modulePath . '/css/style.css';

   
    return array(
        'musicbox_artist_mobileview_item' => $base + array(
                'template' => 'artist_profile_from_sub',
                'variables' => array(
                    

                    'boots_js' => $boots_js,
                    'bootsmin_js'=> $bootsmin_js,
                    'boots_css' => $boots_css,
                    'main_css'=> $main_css,
                    ),
            ),
    );
	
}









?>













































