<?php

/**
 * Implements hook_menu().
 */
function musicbox_forgot_password_menu() {
	$items = array();
    $items['user_password'] = array(
    
   'page callback' => 'musicbox_forgot_passwoerd_call_back',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
	  );
	  
   $items['email_password'] = array(
    
   'page callback' => 'musicbox_email_password_call_back',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
	  );
	
  return $items;
 
}
 function musicbox_email_password_call_back(){
	 
	 	$uniqueId= time();
	if(isset($_POST['usersubmit']) and $_POST['usersubmit']=='E-mail new password')
		{
$to = $_POST['useremail']; // to e-mail address			
$userid = _get_username_by_email($to);
$from = "web@kreativekrib.com";

$requser = user_load($userid);

if($userid == 0){
	$message = "<html><body>


	<p>Hi </p>

	<p>There is no user account according to your mail address</p>

<p>You may register new account in by clicking this link or copying and pasting it to your browser:</p>

<p>
https://kreativekrib.com/musicbox.lk/user/register</p>

<p>
-- Music Box team </p>



</body></html>";
	
}else{
	
	$message = "<html><body>


	<p>Hi ".$requser->name."</p>

	<p>A request to reset the password for your account has been made at Music Box.</p>

<p>You may now log in by clicking this link or copying and pasting it to your browser:</p>
<p>
https://kreativekrib.com/musicbox.lk/reset_password/".$to."/".$userid."</p>


<p>
-- Music Box team </p>



</body></html>";
}


	

	




 
$params = array(
  'subject' => "Musicbox User Reset Password ",
  'body' => $message,
);

// Send out the e-mail.
drupal_mail('musicbox_forgot_password', 'usermail', $to, language_default(), $params, $from);
echo "<script>
window.location.href='/musicbox.lk/user';
alert('Check your email inbox ');
</script>";	
		
		}
	 
 }
function musicbox_forgot_password_mail($key, &$message, $params){


	// Set the mail content type to html to send an html e-mail (optional).
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';

  // Grab the subject and body from params and add it to the message.
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body']; // Drupal 7
  //$message['body'] = $params['body']; // Drupal 6, I think

  switch ($key) {
    case "usermail":
      // Make other changes here if desired...
      break;
  }
	
	
	}  
function musicbox_forgot_passwoerd_call_back(){
	
	 print theme('forgot_passwoerd_call_back_item');
}

  
function musicbox_forgot_password_theme() {
    $modulePath = drupal_get_path('module', 'musicbox_forgot_password');
	
    $base = array(
        'path' => $modulePath.'/templates',
    );
    $boots_js = $modulePath . '/js/bootstrap.js';
    $bootsmin_js = $modulePath . '/js/bootstrap.min.js';

    $boots_css = $modulePath . '/css/bootstrap.css';
    $main_css = $modulePath . '/css/style.css';

   
    return array(
        'forgot_passwoerd_call_back_item' => $base + array(
                'template' => 'user_password_temp',
                'variables' => array(
                    

                    'boots_js' => $boots_js,
                    'bootsmin_js'=> $bootsmin_js,
                    'boots_css' => $boots_css,
                    'main_css'=> $main_css,
                    ),
            ),
    );
}


