<?php

/**
 * Implements hook_menu().
 */
function musicbox_reset_password_menu() {
	$items = array();
    $items['reset_password/%'] = array(
    
   'page callback' => 'musicbox_reset_password_call_back',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
	  );
	  

	
  return $items;
 
}

 
function musicbox_reset_password_call_back(){
	
	 print theme('_reset_password_call_back_item');
}

  
function musicbox_reset_password_theme() {
    $modulePath = drupal_get_path('module', 'musicbox_reset_password');
	
    $base = array(
        'path' => $modulePath.'/templates',
    );
    $boots_js = $modulePath . '/js/bootstrap.js';
    $bootsmin_js = $modulePath . '/js/bootstrap.min.js';

    $boots_css = $modulePath . '/css/bootstrap.css';
    $main_css = $modulePath . '/css/style.css';

   
    return array(
        '_reset_password_call_back_item' => $base + array(
                'template' => 'musicbox_reset_password_temp',
                'variables' => array(
                    

                    'boots_js' => $boots_js,
                    'bootsmin_js'=> $bootsmin_js,
                    'boots_css' => $boots_css,
                    'main_css'=> $main_css,
                    ),
            ),
    );
}


