<?php

/**
 * Implements hook_menu().
 */
function musicbox_artist_post_status_menu(){
    $items = array();
    $items['status'] = array(
        'page callback' => 'musicbox_artist_post_status_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_form()
 */
function musicbox_artist_post_status_page() {
    print theme('musicbox_artist_post_status_page_theme');
}



/**
 * Implements hook_theme()
 * @return type
 */
function musicbox_artist_post_status_theme() {
    $modulePath = drupal_get_path('module', 'musicbox_artist_post_status');
	
    $base = array(
        'path' => $modulePath.'/templates',
    );
    $boots_js = $modulePath . '/js/bootstrap.js';
    $bootsmin_js = $modulePath . '/js/bootstrap.min.js';

    $boots_css = $modulePath . '/css/bootstrap.css';
    $main_css = $modulePath . '/css/style.css';

   
    return array(
        'musicbox_artist_post_status_page_theme' => $base + array(
                'template' => 'musicbox_artist_post_status_temp',
                'variables' => array(
                    

                    'boots_js' => $boots_js,
                    'bootsmin_js'=> $bootsmin_js,
                    'boots_css' => $boots_css,
                    'main_css'=> $main_css,
                    ),
            ),
    );
}




